### ISSUE TITLE
Publish new version with the updated dependencies

### ISSUE THREAD

**Issue by jasongilman** [rksm/node-nrepl-client#8]
The current version of nREPL-client on npm is 0.2.3 published a year ago. You updated some dependencies after that with this commit https://github.com/rksm/node-nrepl-client/commit/da17768d0c2a63478233ab63d5e1ec121e0db834#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 but haven't pushed a new version to npm yet.

I found issues with 0.2.3 that seem to stem from the prior bencode version. Can you push a new version of nREPL-client with the dependency changes you made?

I've been relying on this library for [Proto REPL](https://github.com/jasongilman/proto-repl). I must have tried all of the JavaScript nREPL libraries and this was definitely the best one for me. I was pointing my dependencies directly at github but that's causing [issues for some users](https://github.com/jasongilman/proto-repl/issues/50). I'd like to just use a real published version.

Thanks!

**Comment by rksm** [comment]
Sorry for not being responsive. nrepl-client@0.3.0 is published now.
